package:
  name: ecmwf-api-client
  version: "1.4.2"

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install ecmwf-api-client"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - ecmwfapi

about:
  home: https://software.ecmwf.int/wiki/display/WEBAPI 
  license: Apache 2.0
  summary: 'Python client for ECMWF web services API.'

extra:
  recipe-maintainers:
    - Ohjeah
