package:
  name: ecmwf-api-client
  version: "1.4"

source:
  fn: ecmwf-api-client-python.tgz
  url: https://software.ecmwf.int/wiki/download/attachments/56664858/ecmwf-api-client-python.tgz
  sha256: 423331f2ace3b247ff0d7db8c96952003136b5859ad0840a045c311ee857bcfb

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - ecmwfapi

about:
  home: https://software.ecmwf.int/wiki/display/WEBAPI 
  license: Apache 2.0
  summary: 'Python client for ECMWF web services API.'

extra:
  recipe-maintainers:
    - Ohjeah
