travis:
  secure:
    BINSTAR_TOKEN: bC7GCRaSuMc2ElluKHMK/osmyV5MtrdniCXVr1iEHdTAArFKN6Fke+8d1NJsOzrwBw0roMZyv3c3Zq3ly5pIQI753qoFxrjKtn2rB5XpnWsT5DLyZxlzNLFaeuDywB1m2PBkCTFXWv2eq6b6BN1H6hJcitO2j6Wm4WFhL6hwrsb9hfOlrYBr+CMZVf0OmMj+01jhYPyeYCdTbEUbB4WDcVDRT4+5cv6Wkk60E0gZXDB64Sg51ED0VlpY79//atuJRnOamh0+eK2MI8k29seWpmW4wRUZIg9HUdRqiwZ8BrRNkI5isIIBVt830unjp/Z2Wn8C69GTEnIagFwQCrN0QQZIy2uW08ciGBlx6H9taySr5xb4/DjEGb3zYw6buJxOlSfnUVoHHCJY0f8h3ZAsLUVvRuFWLJWmLmIqpjLiadgN9Jjnf8fR3Yu4ykr1clpdLiTrB30Q2Ez9LqNUCmBGErysyUJuRzQ/Vm6ZVwITvK7LvjhmaKBFSHVo+Vk+fa2pq2t6q3OwcAuX54CtaGhd9L5dxDiWRWosQ8PzsE+/WqD0zUwStVr4w2W3OO7AVD9ReB2CFG/2O3Q1mmnZFL6xKd/VbFe9RihHlZzm5SzTpThyVvQD8rfuJjc0DzE3BbmVeoUM1686n8ycEDmi6u+Lrv09kUw/PtMukNVPbPfsAps=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
