travis:
  secure:
    BINSTAR_TOKEN: w0gK68my/I6pRcQ/Mr/eCN9uQd6NXB3hfJTCrfnbbJxjTvGkkg+Va8G4ttBL6v74EMwxdNCEP9+Whx7+2xS4CTRK0aS5BvFwh4E2k7gH4TKyXwl6mfc4Are5LhRM5WMOZET5qUP+Bcxn1BQAENM0s+WDoBSNR9lxwjJeJFGaAEVQlAzIFRDtQy3hlGMeTK2f2ZkNLzycROz9fXfxYpw56zvU+aKDEUyDHpkrjXD8MYljSLVmTkg55KiGe/SWHRYM7xUvglppnX5LQsMiaO5HkXmQwGMXGNMD8Fpfbl6+UDcR8CIvOT19VB6iEgb6WhNG+SyFol3XkovWUTadLN6cHNMThnujlfbMWni+XTtkpqhM9+pixKwKYHofjsRQR6EKmbBzAklSoZRofkSheRiZ5rOH9aROkJ93hshBpf1+ATxAKnsI7GOMje9Lg6NOGqqRgIAs7jbS+gN7dRPYfUm9c9gPPQmRQHL7N4Oi1pL1yKNT2Z1/6mlaGDELe952TJXo6nJV9N1TtnH/EF5zH23TObag5vkg/MZKn0BxgdaTSPeDauhtG94gp2jaaoK+qIidGwTGiZGELu/el1g9zKSGS1U52vFBZ03XnTarDUTD2k3Z+zivDOKgBhri9y4LBKfs5UM6+L7g3IqcY1/81fFVresGuYodIrtD2GoU0hju9V8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
