travis:
  secure:
    BINSTAR_TOKEN: m2zzjlZZVykdtsuhuB5/mD4eKk5/95vybY0tKDIQf1PsCNW2e4V7XSiY7Om9Y9JN219HT7wqgCyfTisctPa9w7mV2ilL2EQKUMrmM4Pm3NjPPoggtoW/5AzBO4IsrskG4y9KGEuCw5JyIJEjSG9RUiqo7zfLTWs4t7h8kl8QVfjpmx4AYP198XIY9ukgNJVswcMd837MdYpB1Fc02htXxm3YtBfTCE0kTiYBKY6KxSKgXyELKYwhd40OW7VMcyJc+Zdc+kjfX8Es4wXhAVHE19HTbqGpeqvSaaQrGKF5tIF9LOuX72P1Cd6lEoXbPKq/plAQfmL8Cln8jG2KeiZ+4P84NPkHjyWA2SEtHIzQe9s4tNoR3+F0oVK7qG+FMq6vsQx6s2J199oDyJNFXMNdtsudYawVUYO68JcbYv+Uadc+XVZqK2DQgToLHHE1G3iOz1PYEUrZ2VdY6av+GHxb7RwBkZkewGOrrj3zJQro7GLrOhaJKm5Unz7oJciS6f6VILyaM8nVdRLJyqDSQRQPU/Z03ETYW4JfVETdZ60+TY2nrUlqFja2bAfEQ1JEzdzHZKoxWQ690Xg8RSpq8gLWfwd4dz0BlEHqox4sq6QQcQTSr1HGytgwjwf/1LPBar2cttn4l4k8e4Dishx8SFyg1tKFsSiyMQL104/c+URlfyA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
